### ISSUE TITLE
Fix NPE in ParserXMLFileHelper.createCamelURIInstance(ParserXMLFileHelper.java:175

### ISSUE THREAD

**Issue by apupier** [camel-tooling/camel-language-server#176]
```
Starting Camel Language Server...
Waiting for a client connection...
Setting client pid to 1464101444
didOpen: TextDocumentItem [
  uri = "dummyUri.xml"
  languageId = "LANGUAGE_ID_APACHE_CAMEL"
  version = 0
  text = "<from uri="" xmlns="http://camel.apache.org/schema/spring"></from>\n"
]
completion: dummyUri.xml
Stopping language server
sleep interrupted
java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method)
	at com.github.cameltooling.lsp.internal.AbstractLanguageServer$CamelServerRunnable.run(AbstractLanguageServer.java:38)
	at java.lang.Thread.run(Thread.java:748)
Starting Camel Language Server...
Waiting for a client connection...
Setting client pid to -1992810420
Checking for client process pid: 1464101444
didOpen: TextDocumentItem [
  uri = "dummyUri.xml"
  languageId = "LANGUAGE_ID_APACHE_CAMEL"
  version = 0
  text = "<from uri="" xmlns="http://camel.apache.org/schema/spring"></from>\n"
]
completion: dummyUri.xml

java.lang.InterruptedException
	at java.lang.ProcessImpl.waitFor(ProcessImpl.java:451)
	at com.github.cameltooling.lsp.internal.AbstractLanguageServer.parentProcessStillRunning(AbstractLanguageServer.java:94)
	at com.github.cameltooling.lsp.internal.AbstractLanguageServer$CamelServerRunnable.run(AbstractLanguageServer.java:36)
	at java.lang.Thread.run(Thread.java:748)
Error searching for corresponding node elements
java.lang.NullPointerException
	at com.github.cameltooling.lsp.internal.parser.ParserXMLFileHelper.createCamelURIInstance(ParserXMLFileHelper.java:175)
	at com.github.cameltooling.lsp.internal.completion.CamelEndpointCompletionProcessor.getCompletions(CamelEndpointCompletionProcessor.java:52)
	at com.github.cameltooling.lsp.internal.CamelTextDocumentService.completion(CamelTextDocumentService.java:87)
	at com.github.cameltooling.lsp.internal.AbstractCamelLanguageServerTest.getCompletionFor(AbstractCamelLanguageServerTest.java:151)
	at com.github.cameltooling.lsp.internal.CamelLanguageServerTest.testDONTProvideCompletionWhenNotAfterURIEqualQuote(CamelLanguageServerTest.java:127)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:383)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:344)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:417)
Stopping language server
```

need to check if the interrupted exception are linked to this NPE also or not (if not, will spawn another issue)

**Comment by tsedmik** [comment]
verified with master branch
